#!/usr/bin/python

import os

my2tp = {
    'plank_oak': 'wood',
    'plank_birch': 'wood_birch',
    'plank_spruce': 'wood_spruce',
    'plank_jungle': 'wood_jungle',
    'log_oak_side': 'tree_side',
    'log_oak_top': 'tree_top',
    'log_spruce_side': 'tree_spruce',
    'log_birch_side': 'tree_birch',
    'log_jungle_side': 'tree_jungle',
    'door_wood_lower': 'doorWood_lower',
    'door_wood_upper': 'doorWood_upper',
    'door_iron_lower': 'doorIron_lower',
    'door_iron_upper': 'doorIron_upper',
    'ladder': 'ladder',
    'trapdoor': 'trapdoor',
    'dirt': 'dirt',
    'farmland_wet': 'farmland_wet',
    'farmland_dry': 'farmland_dry',
    'grass_dirt_side': 'grass_side',
    'grass_snow_side': 'snow_side',
    'grass_side_overlay': 'grass_side_overlay',
    'grass_top': 'grass_top',
    'grass_tall': 'tallgrass',
    'mycelium_top': 'mycel_top',
    'mycelium_dirt_side': 'mycel_side',
    'leaves_oak': 'leaves',
    'leaves_oak_opaque': 'leaves_opaque',
    'leaves_spruce': 'leaves_spruce',
    'leaves_spruce_opaque': 'leaves_spruce_opaque',
    'leaves_jungle': 'leaves_jungle',
    'leaves_jungle_opaque': 'leaves_jungle_opaque',
    'obsidian': 'obsidian',
    'stone_cobble': 'stonebrick',
    'stone_cobble_mossy': 'stoneMoss',
    'stone_smooth': 'stone',
    'stone_bedrock': 'bedrock',
    'stone_white': 'whiteStone',
    'brick_stone_smooth': 'stonebricksmooth',
    'brick_stone_cracked': 'stonebricksmooth_cracked',
    'brick_stone_mossy': 'stonebricksmooth_mossy',
    'brick_stone_chiseled': 'stonebricksmooth_carved',
    'brick_red': 'brick',
    'brick_nether': 'netherBrick',
    'gravel': 'gravel',
    'sand': 'sand',
    'stone_sandstone_top': 'sandstone_top',
    'stone_sandstone_side': 'sandstone_side',
    'stone_sandstone_smooth': 'sandstone_smooth',
    'stone_sandstone_carved': 'sandstone_carved',
    'stone_sandstone_bottom': 'sandstone_bottom',
    'clay': 'clay',
    'snow': 'snow',

    'ore_gold': 'oreGold',
    'ore_coal': 'oreCoal',
    'ore_redstone': 'oreRedstone',
    'ore_iron': 'oreIron',
    'ore_lapis_lazuli': 'oreLapis',
    'ore_emerald': 'oreEmerald',
    'ore_diamond': 'oreDiamond',

    'block_gold': 'blockGold',
    'block_diamond': 'blockDiamond',
    'block_emerald': 'blockEmerald',
    'block_iron': 'blockIron',
    'block_redstone': 'blockRedstone',
    'block_lapis_lazuli': 'blockLapis',
    'block_quartz_side': 'quartzblock_side',
    'block_quartz_top': 'quartzblock_top',
    'block_quartz_bottom': 'quartzblock_bottom',
    'block_quartz_pillar_side': 'quartzblock_lines',
    'block_quartz_pillar_top': 'quartzblock_lines_top',
    'block_quartz_chiseled_side': 'quartzblock_chiseled',
    'block_quartz_chiseled_top': 'quartzblock_chiseled_top',

    'bars_iron': 'fenceIron',

    'glass': 'glass',
    'glass_thin_top': 'thinglass_top',

    'wool_white': 'cloth_0',
    'wool_orange': 'cloth_1',
    'wool_magenta': 'cloth_2',
    'wool_lightblue': 'cloth_3',
    'wool_yellow': 'cloth_4',
    'wool_lime': 'cloth_5',
    'wool_pink': 'cloth_6',
    'wool_gray': 'cloth_7',
    'wool_lightgray': 'cloth_8',
    'wool_cyan': 'cloth_9',
    'wool_purple': 'cloth_10',
    'wool_blue': 'cloth_11',
    'wool_brown': 'cloth_12',
    'wool_green': 'cloth_13',
    'wool_red': 'cloth_14',
    'wool_black': 'cloth_15',
    'bed_head_top': 'bed_head_top',
    'bed_feet_top': 'bed_feet_top',
    'bed_head_side': 'bed_head_side',
    'bed_feet_side': 'bed_feet_side',
    'bed_head_end': 'bed_head_end',
    'bed_feet_end': 'bed_feet_end',
    'anvil_base': 'anvil_base',
    'anvil_top': 'anvil_top',
    'anvil_top_damaged_1': 'anvil_top_damaged_1',
    'anvil_top_damaged_2': 'anvil_top_damaged_2',
    'brewing_stand': 'brewingStand',
    'brewing_stand_base': 'brewingStand_base',
    'cauldron_bottom': 'cauldron_bottom',
    'cauldron_inner': 'cauldron_inner',
    'cauldron_side': 'cauldron_side',
    'cauldron_top': 'cauldron_top',
    'itemframe_back': 'itemframe_back',

    'beacon': 'beacon',

    'rail_straight': 'rail',
    'rail_turn': 'rail_turn',
    'rail_detector': 'detectorRail',
    'rail_activator_off': 'activatorRail',
    'rail_activator_on': 'activatorRail_powered',
    'rail_powered_off': 'goldenRail',
    'rail_powered_on': 'goldenRail_powered',

    'cobweb': 'web',
    'plant_dandelion': 'flower',
    'plant_rose': 'rose',
    'plant_dead': 'deadbush',
    'plant_fern': 'fern',
    'flower_pot': 'flowerPot',
    'lilypad': 'waterlily',
    'sapling_oak': 'sapling',
    'sapling_spruce': 'sapling_spruce',
    'sapling_birch': 'sapling_birch',
    'sapling_jungle': 'sapling_jungle',

    'crops_0': 'crops_0',
    'crops_1': 'crops_1',
    'crops_2': 'crops_2',
    'crops_3': 'crops_3',
    'crops_4': 'crops_4',
    'crops_5': 'crops_5',
    'crops_6': 'crops_6',
    'crops_7': 'crops_7',
    'carrots_0': 'carrots_0',
    'carrots_1': 'carrots_1',
    'carrots_2': 'carrots_2',
    'carrots_3': 'carrots_3',
    'potatoes_0': 'potatoes_0',
    'potatoes_1': 'potatoes_1',
    'potatoes_2': 'potatoes_2',
    'potatoes_3': 'potatoes_3',
    'cactus_side': 'cactus_side',
    'cactus_bottom': 'cactus_bottom',
    'cactus_top': 'cactus_top',
    'cake_top': 'cake_top',
    'cake_bottom': 'cake_bottom',
    'cake_side': 'cake_side',
    'cake_inner': 'cake_inner',
    'cocoa_0': 'cocoa_0',
    'cocoa_1': 'cocoa_1',
    'cocoa_2': 'cocoa_2',
    'melon_side': 'melon_side',
    'melon_top': 'melon_top',
    'pumpkin_side': 'pumpkin_side',
    'pumpkin_top': 'pumpkin_top',
    'pumpkin_off': 'pumpkin_face',
    'pumpkin_on': 'pumpkin_jack',
    'mushroom_skin_stem': 'mushroom_skin_stem',
    'mushroom_skin_red': 'mushroom_skin_red',
    'mushroom_skin_brown': 'mushroom_skin_brown',
    'mushroom_inside': 'mushroom_inside',
    'mushroom_brown': 'mushroom_brown',
    'mushroom_red': 'mushroom_red',
    'netherwart_stage_0': 'netherStalk_0',
    'netherwart_stage_1': 'netherStalk_1',
    'netherwart_stage_2': 'netherStalk_2',
    'sugarcane': 'reeds',
    'stem_straight': 'stem_straight',
    'stem_bent': 'stem_bent',

    'dragon_egg': 'dragonEgg',
    'enchantment_bottom': 'enchantment_bottom',
    'enchantment_side': 'enchantment_side',
    'enchantment_top': 'enchantment_top',
    'endframe_eye': 'endframe_eye',
    'endframe_side': 'endframe_side',
    'endframe_top': 'endframe_top',

    'destroy_0': 'destroy_0',
    'destroy_1': 'destroy_1',
    'destroy_2': 'destroy_2',
    'destroy_3': 'destroy_3',
    'destroy_4': 'destroy_4',
    'destroy_5': 'destroy_5',
    'destroy_6': 'destroy_6',
    'destroy_7': 'destroy_7',
    'destroy_8': 'destroy_8',
    'destroy_9': 'destroy_9',

    'ice': 'ice',
    'water': 'water',
    'water_flow': 'water_flow',
    'lava': 'lava',
    'lava_flow': 'lava_flow',
    'portal': 'portal',
    'fire_0': 'fire_0',
    'fire_1': 'fire_1',

    'monster_spawner': 'mobSpawner',

    'torch': 'torch',
    'torch_redstone_off': 'redtorch',
    'torch_redstone_on': 'redtorch_lit',
    'redstone_dust_line': 'redstoneDust_line',
    'redstone_dust_line_overlay': 'redstoneDust_line_overlay',
    'redstone_dust_cross': 'redstoneDust_cross',
    'redstone_dust_cross_overlay': 'redstoneDust_cross_overlay',
    'redstone_lamp_off': 'redstoneLight',
    'redstone_lamp_on': 'redstoneLight_lit',
    'redstone_repeater_on': 'repeater',
    'redstone_repeater_off': 'repeater_lit',
    'comparator_off': 'comparator',
    'comparator_on': 'comparator_lit',
    'daylight_detector_top': 'daylightDetector_top',
    'daylight_detector_side': 'daylightDetector_side',
    'lever': 'lever',
    'trip_wire': 'tripWire',
    'trip_wire_source': 'tripWireSource',
    'tnt_bottom': 'tnt_bottom',
    'tnt_top': 'tnt_top',
    'tnt_side': 'tnt_side',
    'hopper': 'hopper',
    'hopper_inside': 'hopper_inside',
    'hopper_top': 'hopper_top',
    'piston_bottom': 'piston_bottom',
    'piston_inner_top': 'piston_inner_top',
    'piston_side': 'piston_side',
    'piston_top_sticky': 'piston_top_sticky',
    'piston_top': 'piston_top',

    'sponge': 'sponge',
    'vine': 'vine',

    'furnace_front_off': 'furnace_front',
    'furnace_front_on': 'furnace_front_lit',
    'furnace_side': 'furnace_side',
    'furnace_top': 'furnace_top',
    'dispenser_front': 'dispenser_front',
    'dispenser_vertical_front': 'dispenser_front_vertical',
    'dropper_front': 'dropper_front',
    'dropper_vertical_front': 'dropper_front_vertical',

    'crafting_table_side': 'workbench_side',
    'crafting_table_top': 'workbench_top',
    'crafting_table_front': 'workbench_front',
    'command_block': 'commandBlock',
    'bookshelf': 'bookshelf',
    'note_block': 'musicBlock',
    'jukebox': 'jukebox_top',

    'netherrack': 'hellrock',
    'ore_nether_quartz': 'netherquartz',
    'soulsand': 'hellsand',
    'glowstone': 'lightgem',
}

myorder = [
    'plank_oak',
    'plank_birch',
    'plank_spruce',
    'plank_jungle',
    'log_oak_side',
    'log_oak_top',
    'log_spruce_side',
    'log_birch_side',
    'log_jungle_side',
    'door_wood_lower',
    'door_wood_upper',
    'door_iron_lower',
    'door_iron_upper',
    'ladder',
    'trapdoor',
    'dirt',
    'farmland_wet',
    'farmland_dry',
    'grass_dirt_side',
    'grass_snow_side',
    'grass_side_overlay',
    'grass_top',
    'grass_tall',
    'mycelium_top',
    'mycelium_dirt_side',
    'leaves_oak',
    'leaves_oak_opaque',
    'leaves_spruce',
    'leaves_spruce_opaque',
    'leaves_jungle',
    'leaves_jungle_opaque',
    'obsidian',
    'stone_cobble',
    'stone_cobble_mossy',
    'stone_smooth',
    'stone_bedrock',
    'stone_white',
    'brick_stone_smooth',
    'brick_stone_cracked',
    'brick_stone_mossy',
    'brick_stone_chiseled',
    'brick_red',
    'brick_nether',
    'gravel',
    'sand',
    'stone_sandstone_top',
    'stone_sandstone_side',
    'stone_sandstone_smooth',
    'stone_sandstone_carved',
    'stone_sandstone_bottom',
    'clay',
    'snow',
    None,
    'ore_gold',
    'ore_coal',
    'ore_redstone',
    'ore_iron',
    'ore_lapis_lazuli',
    'ore_emerald',
    'ore_diamond',
    None,
    'block_gold',
    'block_diamond',
    'block_emerald',
    'block_iron',
    'block_redstone',
    'block_lapis_lazuli',
    'block_quartz_side',
    'block_quartz_top',
    'block_quartz_bottom',
    'block_quartz_pillar_side',
    'block_quartz_pillar_top',
    'block_quartz_chiseled_side',
    'block_quartz_chiseled_top',
    None,
    'bars_iron',
    None,
    'glass',
    'glass_thin_top',
    None,
    'wool_white',
    'wool_orange',
    'wool_magenta',
    'wool_lightblue',
    'wool_yellow',
    'wool_lime',
    'wool_pink',
    'wool_gray',
    'wool_lightgray',
    'wool_cyan',
    'wool_purple',
    'wool_blue',
    'wool_brown',
    'wool_green',
    'wool_red',
    'wool_black',
    'bed_head_top',
    'bed_feet_top',
    'bed_head_side',
    'bed_feet_side',
    'bed_head_end',
    'bed_feet_end',
    'anvil_base',
    'anvil_top',
    'anvil_top_damaged_1',
    'anvil_top_damaged_2',
    'brewing_stand',
    'brewing_stand_base',
    'cauldron_bottom',
    'cauldron_inner',
    'cauldron_side',
    'cauldron_top',
    'itemframe_back',
    None,
    'beacon',
    None,
    'rail_straight',
    'rail_turn',
    'rail_detector',
    'rail_activator_off',
    'rail_activator_on',
    'rail_powered_off',
    'rail_powered_on',
    None,
    'cobweb',
    'plant_dandelion',
    'plant_rose',
    'plant_dead',
    'plant_fern',
    'flower_pot',
    'lilypad',
    'sapling_oak',
    'sapling_spruce',
    'sapling_birch',
    'sapling_jungle',
    None,
    'crops_0',
    'crops_1',
    'crops_2',
    'crops_3',
    'crops_4',
    'crops_5',
    'crops_6',
    'crops_7',
    'carrots_0',
    'carrots_1',
    'carrots_2',
    'carrots_3',
    'potatoes_0',
    'potatoes_1',
    'potatoes_2',
    'potatoes_3',
    'cactus_side',
    'cactus_bottom',
    'cactus_top',
    'cake_top',
    'cake_bottom',
    'cake_side',
    'cake_inner',
    'cocoa_0',
    'cocoa_1',
    'cocoa_2',
    'melon_side',
    'melon_top',
    'pumpkin_side',
    'pumpkin_top',
    'pumpkin_off',
    'pumpkin_on',
    'mushroom_skin_stem',
    'mushroom_skin_red',
    'mushroom_skin_brown',
    'mushroom_inside',
    'mushroom_brown',
    'mushroom_red',
    'netherwart_stage_0',
    'netherwart_stage_1',
    'netherwart_stage_2',
    'sugarcane',
    'stem_straight',
    'stem_bent',
    None,
    'dragon_egg',
    'enchantment_bottom',
    'enchantment_side',
    'enchantment_top',
    'endframe_eye',
    'endframe_side',
    'endframe_top',
    None,
    'destroy_0',
    'destroy_1',
    'destroy_2',
    'destroy_3',
    'destroy_4',
    'destroy_5',
    'destroy_6',
    'destroy_7',
    'destroy_8',
    'destroy_9',
    None,
    'ice',
    'water',
    'water_flow',
    'lava',
    'lava_flow',
    'portal',
    'fire_0',
    'fire_1',
    None,
    'monster_spawner',
    None,
    'torch',
    'torch_redstone_off',
    'torch_redstone_on',
    'redstone_dust_line',
    'redstone_dust_line_overlay',
    'redstone_dust_cross',
    'redstone_dust_cross_overlay',
    'redstone_lamp_off',
    'redstone_lamp_on',
    'redstone_repeater_on',
    'redstone_repeater_off',
    'comparator_off',
    'comparator_on',
    'daylight_detector_top',
    'daylight_detector_side',
    'lever',
    'trip_wire',
    'trip_wire_source',
    'tnt_bottom',
    'tnt_top',
    'tnt_side',
    'hopper',
    'hopper_inside',
    'hopper_top',
    'piston_bottom',
    'piston_inner_top',
    'piston_side',
    'piston_top_sticky',
    'piston_top',
    None,
    'sponge',
    'vine',
    None,
    'furnace_front_off',
    'furnace_front_on',
    'furnace_side',
    'furnace_top',
    'dispenser_front',
    'dispenser_vertical_front',
    'dropper_front',
    'dropper_vertical_front',
    None,
    'crafting_table_side',
    'crafting_table_top',
    'crafting_table_front',
    'command_block',
    'bookshelf',
    'note_block',
    'jukebox',
    None,
    'netherrack',
    'ore_nether_quartz',
    'soulsand',
    'glowstone',
]


tp2rp = {
"textures/blocks/activatorRail.png": "textures/blocks/rail_activator.png",
"textures/blocks/activatorRail_powered.png": "textures/blocks/rail_activator_powered.png",
"textures/blocks/detectorRail.png": "textures/blocks/rail_detector.png",
"textures/blocks/detectorRail_on.png": "textures/blocks/rail_detector_powered.png",
"textures/blocks/goldenRail.png": "textures/blocks/rail_golden.png",
"textures/blocks/goldenRail_powered.png": "textures/blocks/rail_golden_powered.png",
"textures/blocks/rail.png": "textures/blocks/rail_normal.png",
"textures/blocks/rail_turn.png": "textures/blocks/rail_normal_turned.png",
"textures/blocks/anvil_base.png": "textures/blocks/anvil_base.png",
"textures/blocks/anvil_top.png": "textures/blocks/anvil_top_damaged_0.png",
"textures/blocks/anvil_top_damaged_1.png": "textures/blocks/anvil_top_damaged_1.png",
"textures/blocks/anvil_top_damaged_2.png": "textures/blocks/anvil_top_damaged_2.png",
"textures/blocks/crops_0.png": "textures/blocks/wheat_stage_0.png",
"textures/blocks/crops_1.png": "textures/blocks/wheat_stage_1.png",
"textures/blocks/crops_2.png": "textures/blocks/wheat_stage_2.png",
"textures/blocks/crops_3.png": "textures/blocks/wheat_stage_3.png",
"textures/blocks/crops_4.png": "textures/blocks/wheat_stage_4.png",
"textures/blocks/crops_5.png": "textures/blocks/wheat_stage_5.png",
"textures/blocks/crops_6.png": "textures/blocks/wheat_stage_6.png",
"textures/blocks/crops_7.png": "textures/blocks/wheat_stage_7.png",
"textures/blocks/potatoes_0.png": "textures/blocks/potatoes_stage_0.png",
"textures/blocks/potatoes_1.png": "textures/blocks/potatoes_stage_1.png",
"textures/blocks/potatoes_2.png": "textures/blocks/potatoes_stage_2.png",
"textures/blocks/potatoes_3.png": "textures/blocks/potatoes_stage_3.png",
"textures/blocks/carrots_0.png": "textures/blocks/carrots_stage_0.png",
"textures/blocks/carrots_1.png": "textures/blocks/carrots_stage_1.png",
"textures/blocks/carrots_2.png": "textures/blocks/carrots_stage_2.png",
"textures/blocks/carrots_3.png": "textures/blocks/carrots_stage_3.png",
"textures/blocks/stem_bent.png": "textures/blocks/pumpkin_stem_connected.png",
"textures/blocks/stem_straight.png": "textures/blocks/pumpkin_stem_disconnected.png",
"textures/blocks/stem_bent.png": "textures/blocks/melon_stem_connected.png",
"textures/blocks/stem_straight.png": "textures/blocks/melon_stem_disconnected.png",
"textures/blocks/melon_side.png": "textures/blocks/melon_side.png",
"textures/blocks/melon_top.png": "textures/blocks/melon_top.png",
"textures/blocks/netherStalk_0.png": "textures/blocks/nether_wart_stage_0.png",
"textures/blocks/netherStalk_1.png": "textures/blocks/nether_wart_stage_1.png",
"textures/blocks/netherStalk_2.png": "textures/blocks/nether_wart_stage_2.png",
"textures/blocks/cloth_0.png": "textures/blocks/wool_colored_white.png",
"textures/blocks/cloth_1.png": "textures/blocks/wool_colored_orange.png",
"textures/blocks/cloth_2.png": "textures/blocks/wool_colored_magenta.png",
"textures/blocks/cloth_3.png": "textures/blocks/wool_colored_light_blue.png",
"textures/blocks/cloth_4.png": "textures/blocks/wool_colored_yellow.png",
"textures/blocks/cloth_5.png": "textures/blocks/wool_colored_lime.png",
"textures/blocks/cloth_6.png": "textures/blocks/wool_colored_pink.png",
"textures/blocks/cloth_7.png": "textures/blocks/wool_colored_gray.png",
"textures/blocks/cloth_8.png": "textures/blocks/wool_colored_silver.png",
"textures/blocks/cloth_9.png": "textures/blocks/wool_colored_cyan.png",
"textures/blocks/cloth_10.png": "textures/blocks/wool_colored_purple.png",
"textures/blocks/cloth_11.png": "textures/blocks/wool_colored_blue.png",
"textures/blocks/cloth_12.png": "textures/blocks/wool_colored_brown.png",
"textures/blocks/cloth_13.png": "textures/blocks/wool_colored_green.png",
"textures/blocks/cloth_14.png": "textures/blocks/wool_colored_red.png",
"textures/blocks/cloth_15.png": "textures/blocks/wool_colored_black.png",
"textures/blocks/cocoa_0.png": "textures/blocks/cocoa_stage_0.png",
"textures/blocks/cocoa_1.png": "textures/blocks/cocoa_stage_1.png",
"textures/blocks/cocoa_2.png": "textures/blocks/cocoa_stage_2.png",
"textures/blocks/clay.png": "textures/blocks/clay.png",
"textures/blocks/clayHardened.png": "textures/blocks/hardened_clay.png",
"textures/blocks/clayHardenedStained_0.png": "textures/blocks/hardened_clay_stained_white.png",
"textures/blocks/clayHardenedStained_1.png": "textures/blocks/hardened_clay_stained_orange.png",
"textures/blocks/clayHardenedStained_2.png": "textures/blocks/hardened_clay_stained_magenta.png",
"textures/blocks/clayHardenedStained_3.png": "textures/blocks/hardened_clay_stained_light_blue.png",
"textures/blocks/clayHardenedStained_4.png": "textures/blocks/hardened_clay_stained_yellow.png",
"textures/blocks/clayHardenedStained_5.png": "textures/blocks/hardened_clay_stained_lime.png",
"textures/blocks/clayHardenedStained_6.png": "textures/blocks/hardened_clay_stained_pink.png",
"textures/blocks/clayHardenedStained_7.png": "textures/blocks/hardened_clay_stained_gray.png",
"textures/blocks/clayHardenedStained_8.png": "textures/blocks/hardened_clay_stained_silver.png",
"textures/blocks/clayHardenedStained_9.png": "textures/blocks/hardened_clay_stained_cyan.png",
"textures/blocks/clayHardenedStained_10.png": "textures/blocks/hardened_clay_stained_purple.png",
"textures/blocks/clayHardenedStained_11.png": "textures/blocks/hardened_clay_stained_blue.png",
"textures/blocks/clayHardenedStained_12.png": "textures/blocks/hardened_clay_stained_brown.png",
"textures/blocks/clayHardenedStained_13.png": "textures/blocks/hardened_clay_stained_green.png",
"textures/blocks/clayHardenedStained_14.png": "textures/blocks/hardened_clay_stained_red.png",
"textures/blocks/clayHardenedStained_15.png": "textures/blocks/hardened_clay_stained_black.png",
"textures/blocks/destroy_0.png": "textures/blocks/destroy_stage_0.png",
"textures/blocks/destroy_1.png": "textures/blocks/destroy_stage_1.png",
"textures/blocks/destroy_2.png": "textures/blocks/destroy_stage_2.png",
"textures/blocks/destroy_3.png": "textures/blocks/destroy_stage_3.png",
"textures/blocks/destroy_4.png": "textures/blocks/destroy_stage_4.png",
"textures/blocks/destroy_5.png": "textures/blocks/destroy_stage_5.png",
"textures/blocks/destroy_6.png": "textures/blocks/destroy_stage_6.png",
"textures/blocks/destroy_7.png": "textures/blocks/destroy_stage_7.png",
"textures/blocks/destroy_8.png": "textures/blocks/destroy_stage_8.png",
"textures/blocks/destroy_9.png": "textures/blocks/destroy_stage_9.png",
"textures/blocks/blockCoal.png": "textures/blocks/coal_block.png",
"textures/blocks/blockDiamond.png": "textures/blocks/diamond_block.png",
"textures/blocks/blockEmerald.png": "textures/blocks/emerald_block.png",
"textures/blocks/blockGold.png": "textures/blocks/gold_block.png",
"textures/blocks/blockIron.png": "textures/blocks/iron_block.png",
"textures/blocks/blockLapis.png": "textures/blocks/lapis_block.png",
"textures/blocks/blockRedstone.png": "textures/blocks/redstone_block.png",
"textures/blocks/oreCoal.png": "textures/blocks/coal_ore.png",
"textures/blocks/oreDiamond.png": "textures/blocks/diamond_ore.png",
"textures/blocks/oreEmerald.png": "textures/blocks/emerald_ore.png",
"textures/blocks/oreGold.png": "textures/blocks/gold_ore.png",
"textures/blocks/oreIron.png": "textures/blocks/iron_ore.png",
"textures/blocks/oreLapis.png": "textures/blocks/lapis_ore.png",
"textures/blocks/oreRedstone.png": "textures/blocks/redstone_ore.png",
"textures/blocks/rose.png": "textures/blocks/flower_rose.png",
"textures/blocks/flower.png": "textures/blocks/flower_dandelion.png",
"textures/blocks/fire_0.png": "textures/blocks/fire_layer_0.png",
"textures/blocks/fire_1.png": "textures/blocks/fire_layer_1.png",
"textures/blocks/leaves.png": "textures/blocks/leaves_oak.png",
"textures/blocks/leaves_opaque.png": "textures/blocks/leaves_oak_opaque.png",
"textures/blocks/leaves_jungle.png": "textures/blocks/leaves_jungle.png",
"textures/blocks/leaves_jungle_opaque.png": "textures/blocks/leaves_jungle_opaque.png",
"textures/blocks/leaves.png": "textures/blocks/leaves_birch.png",
"textures/blocks/leaves_opaque.png": "textures/blocks/leaves_birch_opaque.png",
"textures/blocks/leaves_spruce.png": "textures/blocks/leaves_spruce.png",
"textures/blocks/leaves_spruce_opaque.png": "textures/blocks/leaves_spruce_opaque.png",
"textures/blocks/tree_side.png": "textures/blocks/log_oak.png",
"textures/blocks/tree_jungle.png": "textures/blocks/log_jungle.png",
"textures/blocks/tree_birch.png": "textures/blocks/log_birch.png",
"textures/blocks/tree_spruce.png": "textures/blocks/log_spruce.png",
"textures/blocks/tree_top.png": "textures/blocks/log_oak_top.png",
"textures/blocks/tree_top.png": "textures/blocks/log_jungle_top.png",
"textures/blocks/tree_top.png": "textures/blocks/log_birch_top.png",
"textures/blocks/tree_top.png": "textures/blocks/log_spruce_top.png",
"textures/blocks/wood.png": "textures/blocks/planks_oak.png",
"textures/blocks/wood_birch.png": "textures/blocks/planks_birch.png",
"textures/blocks/wood_jungle.png": "textures/blocks/planks_jungle.png",
"textures/blocks/wood_spruce.png": "textures/blocks/planks_spruce.png",
"textures/blocks/sapling.png": "textures/blocks/sapling_oak.png",
"textures/blocks/sapling_birch.png": "textures/blocks/sapling_birch.png",
"textures/blocks/sapling_jungle.png": "textures/blocks/sapling_jungle.png",
"textures/blocks/sapling_spruce.png": "textures/blocks/sapling_spruce.png",
"textures/blocks/doorIron_lower.png": "textures/blocks/door_iron_lower.png",
"textures/blocks/doorIron_upper.png": "textures/blocks/door_iron_upper.png",
"textures/blocks/doorWood_lower.png": "textures/blocks/door_wood_lower.png",
"textures/blocks/doorWood_upper.png": "textures/blocks/door_wood_upper.png",
"textures/blocks/workbench_front.png": "textures/blocks/crafting_table_front.png",
"textures/blocks/workbench_side.png": "textures/blocks/crafting_table_side.png",
"textures/blocks/workbench_top.png": "textures/blocks/crafting_table_top.png",
"textures/blocks/bed_feet_end.png": "textures/blocks/bed_feet_end.png",
"textures/blocks/bed_feet_side.png": "textures/blocks/bed_feet_side.png",
"textures/blocks/bed_feet_top.png": "textures/blocks/bed_feet_top.png",
"textures/blocks/bed_head_end.png": "textures/blocks/bed_head_end.png",
"textures/blocks/bed_head_side.png": "textures/blocks/bed_head_side.png",
"textures/blocks/bed_head_top.png": "textures/blocks/bed_head_top.png",
"textures/blocks/beacon.png": "textures/blocks/beacon.png",
"textures/blocks/bedrock.png": "textures/blocks/bedrock.png",
"textures/blocks/bookshelf.png": "textures/blocks/bookshelf.png",
"textures/blocks/brewingStand.png": "textures/blocks/brewing_stand.png",
"textures/blocks/brewingStand_base.png": "textures/blocks/brewing_stand_base.png",
"textures/blocks/whiteStone.png": "textures/blocks/end_stone.png",
"textures/blocks/tnt_bottom.png": "textures/blocks/tnt_bottom.png",
"textures/blocks/tnt_side.png": "textures/blocks/tnt_side.png",
"textures/blocks/tnt_top.png": "textures/blocks/tnt_top.png",
"textures/blocks/sandstone_bottom.png": "textures/blocks/sandstone_bottom.png",
"textures/blocks/sandstone_carved.png": "textures/blocks/sandstone_carved.png",
"textures/blocks/sandstone_side.png": "textures/blocks/sandstone_normal.png",
"textures/blocks/sandstone_smooth.png": "textures/blocks/sandstone_smooth.png",
"textures/blocks/sandstone_top.png": "textures/blocks/sandstone_top.png",
"textures/blocks/cauldron_bottom.png": "textures/blocks/cauldron_bottom.png",
"textures/blocks/cauldron_inner.png": "textures/blocks/cauldron_inner.png",
"textures/blocks/cauldron_side.png": "textures/blocks/cauldron_side.png",
"textures/blocks/cauldron_top.png": "textures/blocks/cauldron_top.png",
"textures/blocks/cake_bottom.png": "textures/blocks/cake_bottom.png",
"textures/blocks/cake_inner.png": "textures/blocks/cake_inner.png",
"textures/blocks/cake_side.png": "textures/blocks/cake_side.png",
"textures/blocks/cake_top.png": "textures/blocks/cake_top.png",
"textures/blocks/quartzblock_bottom.png": "textures/blocks/quartz_block_bottom.png",
"textures/blocks/quartzblock_chiseled.png": "textures/blocks/quartz_block_chiseled.png",
"textures/blocks/quartzblock_chiseled_top.png": "textures/blocks/quartz_block_chiseled_top.png",
"textures/blocks/quartzblock_lines.png": "textures/blocks/quartz_block_lines.png",
"textures/blocks/quartzblock_lines_top.png": "textures/blocks/quartz_block_lines_top.png",
"textures/blocks/quartzblock_side.png": "textures/blocks/quartz_block_side.png",
"textures/blocks/quartzblock_top.png": "textures/blocks/quartz_block_top.png",
"textures/blocks/netherquartz.png": "textures/blocks/quartz_ore.png",
"textures/blocks/stonebrick.png": "textures/blocks/cobblestone.png",
"textures/blocks/stonebricksmooth.png": "textures/blocks/stonebrick.png",
"textures/blocks/stonebricksmooth_carved.png": "textures/blocks/stonebrick_carved.png",
"textures/blocks/stonebricksmooth_cracked.png": "textures/blocks/stonebrick_cracked.png",
"textures/blocks/stonebricksmooth_mossy.png": "textures/blocks/stonebrick_mossy.png",
"textures/blocks/stone.png": "textures/blocks/stone.png",
"textures/blocks/stoneMoss.png": "textures/blocks/cobblestone_mossy.png",
"textures/blocks/stoneslab_side.png": "textures/blocks/stone_slab_side.png",
"textures/blocks/stoneslab_top.png": "textures/blocks/stone_slab_top.png",
"textures/blocks/reeds.png": "textures/blocks/reeds.png",
"textures/blocks/sand.png": "textures/blocks/sand.png",
"textures/blocks/snow.png": "textures/blocks/snow.png",
"textures/blocks/snow_side.png": "textures/blocks/grass_side_snowed.png",
"textures/blocks/grass_side.png": "textures/blocks/grass_side.png",
"textures/blocks/grass_side_overlay.png": "textures/blocks/grass_side_overlay.png",
"textures/blocks/grass_top.png": "textures/blocks/grass_top.png",
"textures/blocks/mushroom_brown.png": "textures/blocks/mushroom_brown.png",
"textures/blocks/mushroom_red.png": "textures/blocks/mushroom_red.png",
"textures/blocks/mushroom_inside.png": "textures/blocks/mushroom_block_inside.png",
"textures/blocks/mushroom_skin_brown.png": "textures/blocks/mushroom_block_skin_brown.png",
"textures/blocks/mushroom_skin_red.png": "textures/blocks/mushroom_block_skin_red.png",
"textures/blocks/mushroom_skin_stem.png": "textures/blocks/mushroom_block_skin_stem.png",
"textures/blocks/redstoneLight.png": "textures/blocks/redstone_lamp_off.png",
"textures/blocks/redstoneLight_lit.png": "textures/blocks/redstone_lamp_on.png",
"textures/blocks/redstoneDust_cross.png": "textures/blocks/redstone_dust_cross.png",
"textures/blocks/redstoneDust_cross_overlay.png": "textures/blocks/redstone_dust_cross_overlay.png",
"textures/blocks/redstoneDust_line.png": "textures/blocks/redstone_dust_line.png",
"textures/blocks/redstoneDust_line_overlay.png": "textures/blocks/redstone_dust_line_overlay.png",
"textures/blocks/redtorch.png": "textures/blocks/redstone_torch_off.png",
"textures/blocks/redtorch_lit.png": "textures/blocks/redstone_torch_on.png",
"textures/blocks/repeater.png": "textures/blocks/repeater_off.png",
"textures/blocks/repeater_lit.png": "textures/blocks/repeater_on.png",
"textures/blocks/pumpkin_face.png": "textures/blocks/pumpkin_face_off.png",
"textures/blocks/pumpkin_jack.png": "textures/blocks/pumpkin_face_on.png",
"textures/blocks/pumpkin_side.png": "textures/blocks/pumpkin_side.png",
"textures/blocks/pumpkin_top.png": "textures/blocks/pumpkin_top.png",
"textures/blocks/piston_bottom.png": "textures/blocks/piston_bottom.png",
"textures/blocks/piston_inner_top.png": "textures/blocks/piston_inner.png",
"textures/blocks/piston_side.png": "textures/blocks/piston_side.png",
"textures/blocks/piston_top.png": "textures/blocks/piston_top_normal.png",
"textures/blocks/piston_top_sticky.png": "textures/blocks/piston_top_sticky.png",
"textures/blocks/farmland_dry.png": "textures/blocks/farmland_dry.png",
"textures/blocks/farmland_wet.png": "textures/blocks/farmland_wet.png",
"textures/blocks/endframe_eye.png": "textures/blocks/endframe_eye.png",
"textures/blocks/endframe_side.png": "textures/blocks/endframe_side.png",
"textures/blocks/endframe_top.png": "textures/blocks/endframe_top.png",
"textures/blocks/enchantment_bottom.png": "textures/blocks/enchanting_table_bottom.png",
"textures/blocks/enchantment_side.png": "textures/blocks/enchanting_table_side.png",
"textures/blocks/enchantment_top.png": "textures/blocks/enchanting_table_top.png",
"textures/blocks/water.png": "textures/blocks/water_still.png",
"textures/blocks/water_flow.png": "textures/blocks/water_flow.png",
"textures/blocks/lava.png": "textures/blocks/lava_still.png",
"textures/blocks/lava_flow.png": "textures/blocks/lava_flow.png",
"textures/blocks/lightgem.png": "textures/blocks/glowstone.png",
"textures/blocks/mobSpawner.png": "textures/blocks/mob_spawner.png",
"textures/blocks/hellrock.png": "textures/blocks/netherrack.png",
"textures/blocks/hellsand.png": "textures/blocks/soul_sand.png",
"textures/blocks/tripWire.png": "textures/blocks/trip_wire.png",
"textures/blocks/tripWireSource.png": "textures/blocks/trip_wire_source.png",
"textures/blocks/commandBlock.png": "textures/blocks/command_block.png",
"textures/blocks/dispenser_front.png": "textures/blocks/dispenser_front_horizontal.png",
"textures/blocks/dispenser_front_vertical.png": "textures/blocks/dispenser_front_vertical.png",
"textures/blocks/dropper_front.png": "textures/blocks/dropper_front_horizontal.png",
"textures/blocks/dropper_front_vertical.png": "textures/blocks/dropper_front_vertical.png",
"textures/blocks/furnace_front.png": "textures/blocks/furnace_front_off.png",
"textures/blocks/furnace_front_lit.png": "textures/blocks/furnace_front_on.png",
"textures/blocks/furnace_side.png": "textures/blocks/furnace_side.png",
"textures/blocks/furnace_top.png": "textures/blocks/furnace_top.png",
"textures/blocks/itemframe_back.png": "textures/blocks/itemframe_background.png",
"textures/blocks/hopper.png": "textures/blocks/hopper_outside.png",
"textures/blocks/hopper_inside.png": "textures/blocks/hopper_inside.png",
"textures/blocks/hopper_top.png": "textures/blocks/hopper_top.png",
"textures/blocks/thinglass_top.png": "textures/blocks/glass_pane_top.png",
"textures/blocks/cactus_bottom.png": "textures/blocks/cactus_bottom.png",
"textures/blocks/cactus_side.png": "textures/blocks/cactus_side.png",
"textures/blocks/cactus_top.png": "textures/blocks/cactus_top.png",
"textures/blocks/daylightDetector_side.png": "textures/blocks/daylight_detector_side.png",
"textures/blocks/daylightDetector_top.png": "textures/blocks/daylight_detector_top.png",
"textures/blocks/jukebox_top.png": "textures/blocks/jukebox_top.png",
"textures/blocks/musicBlock.png": "textures/blocks/jukebox_side.png",
"textures/blocks/musicBlock.png": "textures/blocks/noteblock.png",
"textures/blocks/comparator.png": "textures/blocks/comparator_off.png",
"textures/blocks/comparator_lit.png": "textures/blocks/comparator_on.png",
"textures/blocks/fenceIron.png": "textures/blocks/iron_bars.png",
"textures/blocks/hayBlock.png": "textures/blocks/hay_block_side.png",
"textures/blocks/hayBlock_top.png": "textures/blocks/hay_block_top.png",
"textures/blocks/brick.png": "textures/blocks/brick.png",
"textures/blocks/deadbush.png": "textures/blocks/deadbush.png",
"textures/blocks/dirt.png": "textures/blocks/dirt.png",
"textures/blocks/dragonEgg.png": "textures/blocks/dragon_egg.png",
"textures/blocks/fern.png": "textures/blocks/fern.png",
"textures/blocks/flowerPot.png": "textures/blocks/flower_pot.png",
"textures/blocks/glass.png": "textures/blocks/glass.png",
"textures/blocks/gravel.png": "textures/blocks/gravel.png",
"textures/blocks/ice.png": "textures/blocks/ice.png",
"textures/blocks/ladder.png": "textures/blocks/ladder.png",
"textures/blocks/lever.png": "textures/blocks/lever.png",
"textures/blocks/mycel_side.png": "textures/blocks/mycelium_side.png",
"textures/blocks/mycel_top.png": "textures/blocks/mycelium_top.png",
"textures/blocks/netherBrick.png": "textures/blocks/nether_brick.png",
"textures/blocks/obsidian.png": "textures/blocks/obsidian.png",
"textures/blocks/portal.png": "textures/blocks/portal.png",
"textures/blocks/sponge.png": "textures/blocks/sponge.png",
"textures/blocks/tallgrass.png": "textures/blocks/tallgrass.png",
"textures/blocks/torch.png": "textures/blocks/torch_on.png",
"textures/blocks/trapdoor.png": "textures/blocks/trapdoor.png",
"textures/blocks/vine.png": "textures/blocks/vine.png",
"textures/blocks/waterlily.png": "textures/blocks/waterlily.png",
"textures/blocks/web.png": "textures/blocks/web.png",
}

rp2tp = {}

for my,tp in my2tp.iteritems():
    mypath = "images/" + my + ".png"
    tppath = "textures/blocks/" + tp + ".png"

    rppath = tp2rp[tppath]
    rpname = os.path.basename(rppath).replace(".png", "")

    #print mypath,tppath,rppath
    print "git mv %s %s" % (mypath, rppath)

    rp2tp[rpname] = tp


#for rp in sorted(rp2tp.keys()):
#    print "    %s: '%s'," % (rp, rp2tp[rp])

for my in myorder:
    if my is None:
        print
    else:
        tp = my2tp[my]
        rp = tp2rp["textures/blocks/" + tp + ".png"]
        print "    %s: '%s'," % (os.path.basename(rp).replace(".png", ""), tp)
